main: es.bewom.bewomBit.bewomBit
name: bewomBit
version: 1.0.0
author: www.bewom.es

commands:
   say:
      description: Allow a player to broadcast.
      permission: bewom.say

   fly:
      description: Allow player to fly.
      permission: bewom.fly

   tphere:
      description: Allow a player to tp another player to his location.
      permission: bewom.tphere