main: es.bewom.bewomBit.bewomBit
name: bewomBit
version: 1.0.0
author: www.bewom.es

commands:
   say:
      description: Permite al jugador hablar por el broadcast.
      permission: bewom.admin

   fly:
      description: Permite al jugador volar.
      permission: bewom.admin

   tphere:
      description: Permite al jugador teletransportar a otro jugador donde se encuentra.
      permission: bewom.admin
      
   clear:
      description: Permite al jugador limpiar el inventario.
      permission: bewom.admin
      
   hat:
      description: Permite al jugador ponerse un sombrero.
      permission: bewom.vip