main: es.bewom.bewomBit.bewomBit
name: bewomBit
version: 1.0.0
author: www.bewom.es

commands:
   say:
      description: Permite al jugador hablar por el broadcast.
      permission: bewom.admin

   fly:
      description: Permite al jugador volar.
      permission: bewom.admin

   tphere:
      description: Permite al jugador teletransportar a otro jugador donde se encuentra.
      permission: bewom.admin

   clear:
      description: Permite al jugador limpiar el inventario.
      permission: bewom.admin

   hat:
      description: Permite al jugador ponerse un sombrero.
      permission: bewom.vip

   inv:
      description: Permite al jugador abrir el inventario de otra persona
      permission: bewom.admin

   end:
      description: Permite al jugador abrir el enderchest de otra persona
      permission: bewom.admin

   ender:
      description: Permite al jugador abrir el enderchest de otra persona
      permission: bewom.admin

   enderchest:
      description: Permite al jugador abrir el enderchest
      permission: bewom.vip

   kill:
      description: Permite al jugador matar a otro jugador
      permission: bewom.admin

   suicide:
      description: Permite al jugador suicidarse
      permission: bewom.vip

   heal:
      description: Permite al jugador curarse
      permission: bewom.admin

   congelar:
      description: Algo
      permission: bewom.congelashasdf
      permission: bewom.vip

   seen:
      description: Permite al jugador ver la ultima conexion de otro jugador
      permission: bewom.vip

   kick:
      description: Permite al jugador kickear a otro jugador
      permission: bewom.admin

   mp:
      description: Permite entrar en chats
      permission: bewom.admin

   me:
      description: Permite entrar en chatsew
      permission: bewom.admin
      
   msg:
      description: Permite entrar en chats
      permission: bewom.admin

   tell:
      description: Permite entrar en chats
      permission: bewom.admin
  
   p:
      description: Permite al jugador editar un cofre
      permission: bewom.admin
      
   gm:
      description: Permite al jugador cambiar de gamemode
      permission: bewom.admin
      
   v:
      description: Permite al jugador ocultarse
      permission: bewom.admin
   
   tpa:
      description: Permite al jugador pedir una peticion de tp
      permission: bewom.admin