main: es.bewom.bewomBit.BewomBit
name: bewomBit
version: 1.0.0
author: www.bewom.es

commands:
   say:
      description: Permite al jugador hablar por el broadcast.
      permission: bewom.admin

   fly:
      description: Permite al jugador volar.
      permission: bewom.admin

   tphere:
      description: Permite al jugador teletransportar a otro jugador donde se encuentra.
      permission: bewom.admin

   clear:
      description: Permite al jugador limpiar el inventario.
      permission: bewom.admin

   hat:
      description: Permite al jugador ponerse un sombrero.
      permission: bewom.vip

   inv:
      description: Permite al jugador abrir el inventario de otra persona
      permission: bewom.admin

   end:
      description: Permite al jugador abrir el enderchest de otra persona
      permission: bewom.admin

   ender:
      description: Permite al jugador abrir el enderchest de otra persona
      permission: bewom.admin

   enderchest:
      description: Permite al jugador abrir el enderchest
      permission: bewom.vip

   kill:
      description: Permite al jugador matar a otro jugador
      permission: bewom.admin

   suicide:
      description: Permite al jugador suicidarse
      permission: bewom.vip

   heal:
      description: Permite al jugador curarse
      permission: bewom.admin

   congelar:
      description: Permite al jugador congelar jugadores
      permission: bewom.admin

   seen:
      description: Permite al jugador ver la ultima conexion de otro jugador
      permission: bewom.vip

   kick:
      description: Permite al jugador kickear a otro jugador
      permission: bewom.admin

   mp:
      description: Permite entrar en chats
      permission: bewom.vip

   me:
      description: Permite entrar en chatsew
      permission: bewom.vip

   msg:
      description: Permite entrar en chats
      permission: bewom.vip

   tell:
      description: Permite entrar en chats
      permission: bewom.vip

   p:
      description: Permite al jugador editar un cofre
      permission: bewom.vip

   gm:
      description: Permite al jugador cambiar de gamemode
      permission: bewom.admin

   v:
      description: Permite al jugador ocultarse
      permission: bewom.admin

   tpa:
      description: Permite al jugador pedir una peticion de tp
      permission: bewom.vip

   tpahere:
      description: Permite al jugador pedir una peticion de tp donde el se encuentra
      permission: bewom.vip

   spawner:
      description: Permite al jugador cambiar un spawner
      permission: bewom.admin

   sethome:
      description: Permite al jugador guardar una localizacion
      permission: bewom.vip

   home:
      description: Permite al jugador teletransportarse a una localizacion
      permission: bewom.vip

   delhome:
      description: Permite al jugador teletransportarse a una localizacion
      permission: bewom.vip

   spawn:
      description: Permite al jugador ir al spawn
      permission: bewom.default

   god:
      description: Permite al jugador ser inmortal
      permission: bewom.admin

   lag:
      description: Permite al jugador saber el estado del servidor.
      permission: bewom.default

   tpall:
      description: Permite al jugador tepear telentransportar a todos los jugadores hacia el.
      permission: bewom.admin

   speed:
      description: Permite al jugador cambiar velocidades.
      permission: bewom.admin
      
   ban:
      description: Permite al jugador banear a otro jugador
      permission: bewom.mod
      
   unban:
      description: Permite al jugador desbanear a otro jugador
      permission: bewom.mod
      
   save:
      description: Permite al jugador guardar el servidor
      permission: bewom.mod
      
   xray:
      description: Permite al jugador ver los stats de xray
      permission: bewom.mod

