main: es.bewom.bewomBit.bewomBit
name: bewomBit
version: 1.0.0
author: www.bewom.es

commands:
   say:
      description: This is a demo command.
      permission: bewom.basic

   fly:
      description: Allow a player to fly.
      permission: bewom.fly

   tphere:
      description: This is a demo command.
      permission: bewom.basic
   
   hola:
      description: This is a demo command.
      permission: bewom.basic